app:
    resource: '@AppBundle/Controller/'
    type: annotation
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
Rest:
    type: rest
    resource: AppBundle\Controller\RestController
homepage:
    pattern: /
    defaults: {_controller: AppBundle:Default:index}
resultpage:
    pattern: /result
    defaults: {_controller: AppBundle:Result:index}
resultpage2:   
    pattern: /search/{search}/amountOfresults/{amountOfResults}/page/{page}
    defaults: {_controller: AppBundle:Result:result}
